# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 13:41
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(max_length=300)),
                ('citta', models.CharField(max_length=200)),
                ('stato', models.CharField(max_length=200)),
                ('num_telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('piscina', models.BooleanField(default=False)),
                ('WiFi', models.BooleanField(default=False)),
                ('accesso_disabili', models.BooleanField(default=False)),
                ('ristorante', models.BooleanField(default=False)),
                ('parcheggio', models.BooleanField(default=False)),
                ('palestra', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('descrizione', models.CharField(max_length=1000)),
                ('sito', models.CharField(max_length=600)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazioni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='check_in')),
                ('check_out', models.DateTimeField(verbose_name='check_out')),
            ],
        ),
        migrations.CreateModel(
            name='Stanza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_camera', models.PositiveIntegerField()),
                ('prezzo', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prezzo_festivita', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_persone', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('aria_condizionata', models.BooleanField(default=False)),
                ('camera_fumatori', models.BooleanField(default=False)),
                ('animali', models.BooleanField(default=False)),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBookingApp_2.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='prenotazioni',
            name='id_stanza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBookingApp_2.Stanza'),
        ),
        migrations.AddField(
            model_name='prenotazioni',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='stanza',
            unique_together=set([('id_hotel', 'num_camera')]),
        ),
    ]
