# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBookingApp_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazioni',
            name='check_in',
            field=models.DateField(verbose_name='check_in'),
        ),
        migrations.AlterField(
            model_name='prenotazioni',
            name='check_out',
            field=models.DateField(verbose_name='check_out'),
        ),
    ]
