# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myBookingApp_2', '0002_auto_20180204_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto_value', models.FloatField(default=0.0)),
                ('hotel_voto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_voto_set', to='myBookingApp_2.Hotel')),
                ('user_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_voto_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
