# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBookingApp_2', '0003_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Voto',
        ),
    ]
