# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBookingApp_2', '0005_auto_20180205_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='hotel_voto',
            new_name='hotel_id',
        ),
        migrations.RenameField(
            model_name='voto',
            old_name='user_vote',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='voto',
            old_name='voto_value',
            new_name='voto',
        ),
    ]
