# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 22:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBookingApp_2', '0006_auto_20180205_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='voto',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
