# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 14:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBookingApp_2', '0007_auto_20180205_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazioni',
            name='check_in',
            field=models.DateTimeField(verbose_name='check_in'),
        ),
        migrations.AlterField(
            model_name='prenotazioni',
            name='check_out',
            field=models.DateTimeField(verbose_name='check_out'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='voto',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
